[package]
name = "libdatabase-rs"
authors = ["Jonathan Pallant <jonathan.pallant@ferrous-systems.com>"]
version = "1.0.0"
edition = "2024"

[dependencies]
libdatabase-sys = { version = "1.0.0", path = "../libdatabase-sys" }
