[package]
name = "libdatabase-sys"
authors = ["Jonathan Pallant <jonathan.pallant@ferrous-systems.com>"]
version = "0.1.0"
edition = "2024"

[dependencies]

[build-dependencies]
bindgen = "0.72.1"
cc = "1.2.52"
