manifest-version = 1

[products.ferrocene]
release = "stable-25.11.0"
packages = [
    "rustc-${rustc-host}",
    "rust-std-${rustc-host}",
    "cargo-${rustc-host}",
    "llvm-tools-${rustc-host}",
    "rust-src",
    "rust-std-thumbv7em-none-eabihf",
]
