[package]
name = "rust-program"
authors = ["Jonathan Pallant <jonathan.pallant@ferrous-systems.com>"]
version = "0.1.0"
edition = "2024"

[dependencies]
libdatabase-rs = { version = "0.1.0", path = "../libdatabase-rs" }
