[book]
authors = ["Ferrous Systems"]
language = "en"
src = "src"
title = "Rust Training Slides by Ferrous Systems"

[preprocessor.graphviz]
command = "mdbook-graphviz"

[output.html.playground]
copyable = true          # include the copy button for copying code snippets
